baseURL = "https://turtledev.in/"
languageCode = "en-us"
title = "turtleDev"
theme = "garage"

pygmentsUseClasses = "true"

[params]
    favicon_32 = "/assets/icon.png"
    favicon_16 = "/assets/icon.png"
    custom_css = [
        "/styles/syntax.css"
    ]

[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"
