# CI Configuration
# only commits on 'source' branch are built and deployed.
# this configuration requires the following environment values
# to be set up:
#   * SSH_KEY (github deploy key)
version: 2

jobs:
  build:
    docker:
      # I don't really need golang's image, but circleci's prebuilt
      # images don't contain a simple base os image, so I'm opting for
      # this one, since it's the closest to my purpose.
      - image: circleci/golang:1.10-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "63:99:b3:4d:ec:94:fb:d0:27:84:0e:0c:86:0e:a8:49"
      - checkout
      - run: |
          git config --global user.email "saravjeetamansingh@gmail.com"
          git config --global user.name "turtleDev (via CircleCI)"
          git submodule add -f -b master git@github.com:turtledev/turtledev.github.io public
          rm public/* -r
          ./hugow
          cd public/
          git add .
          git commit -m "build for ${CIRCLE_SHA1}"
          git push