name: deploy-pages

on:
  push:
    branches: [ "source" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: checkout submodules
        run: |
          git submodule update --init
      
      # - name: setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16"

      # - name: create production build
      #   run: |
      #     npm install
      #     npm run build
          
      # - name: upload build to artifact server
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: ./build
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.output.page_url }}
  #   steps:
  #     - id: deployment
  #       uses: actions/deploy-pages@v1